stages:
  - deploy

deploy-job:
  stage:
    deploy
  script:
    - echo "Deploying application..."
      - pip install -r requirements.txt
      - cp -r * /alice2mqtt
      - systemctl restart your_application_service
  only:
    - main